/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author tlatl
 */
public class ChangeUser extends javax.swing.JFrame {

    Login idpw = new Login();
    boolean userCheck = false;
    boolean idpwcheck = false;
    File myFile = new File("User.txt");

    /**
     * Creates new form ChangeUser
     */
    public ChangeUser() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        pw = new javax.swing.JPasswordField();
        newpwCheck = new javax.swing.JPasswordField();
        newpw = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setText(" 아이디 :");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));

        jLabel3.setText("비밀번호 :");
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, 60, -1));

        jLabel4.setText("새 비밀번호 : ");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jLabel5.setText("비밀번호 확인 : ");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));
        jPanel5.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 180, 32));

        jLabel7.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel7.setText("*변경 사항 입력");
        jPanel5.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 20));

        jLabel8.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel8.setText("*현재 사용중인 아이디 비밀번호 입력");
        jPanel5.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, 20));

        jButton3.setFont(new java.awt.Font("맑은 고딕", 0, 18)); // NOI18N
        jButton3.setText("인증");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 250, 30));
        jPanel5.add(pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, 180, 30));
        jPanel5.add(newpwCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 180, 30));
        jPanel5.add(newpw, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 180, 30));

        jButton1.setText("변경");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 300, 40));

        jButton2.setText("회원 탈퇴");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, 300, 40));

        jButton4.setText("뒤로가기");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 430, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            // TODO add your handling code here:
            String temp;
            String[] array;

            FileReader fileReader = new FileReader(myFile);
            BufferedReader reader = new BufferedReader(fileReader);

            while ((temp = reader.readLine()) != null) {
                array = temp.split("/");
                if (id.getText().equals(array[1]) && pw.getText().equals(array[2])) {
                    JOptionPane.showMessageDialog(null, "인증이 완료되었습니다..");
                    id.setEnabled(false);
                    pw.setEnabled(false);
                    userCheck = true;
                    idpwcheck = true;
                    break;
                }
            }
            reader.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(ChangeUser.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ChangeUser.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (idpwcheck == false) {
            JOptionPane.showMessageDialog(null, "인증에 실패했습니다.");
            id.setText("");
            pw.setText("");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if (!newpw.getText().equals(newpwCheck.getText())) {
            JOptionPane.showMessageDialog(null, "새 비밀번호와 확인 비밀번호가 다릅니다. 다시 입력해주세요.");
        } else if (userCheck == false) {
            JOptionPane.showMessageDialog(null, "인증이 완료되지 않았습니다. 인증 후 다시 시도해주십시요");
        } else {

            int result = JOptionPane.showConfirmDialog(null, "비밀번호를 변경하시겠습니까??", "주의!", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.CLOSED_OPTION) {
                JOptionPane.showMessageDialog(null, "비밀번호를 변경하지 않았습니다.");
            } else if (result == JOptionPane.YES_OPTION) {
                
                String temp;
                String[] array = new String[4];
                String dummy = "";
                try {

                    BufferedReader reader = new BufferedReader(new InputStreamReader(new FileInputStream(myFile)));

                    while ((temp = reader.readLine()) != null) {
                        array = temp.split("/");
                        if (id.getText().equals(array[1]) && pw.getText().equals(array[2])) {
                            array[2] = newpw.getText();
                            for (int i = 0; i < 5; i++) {
                                dummy += array[i] + "/";
                            }
                            dummy += "\r\n";
                        } else {
                            dummy += (temp + "\r\n");
                        }
                    }

                    FileWriter fw = new FileWriter("User.txt");
                    fw.write(dummy);

                    reader.close();
                    fw.close();
                    JOptionPane.showMessageDialog(null, "비밀번호가 변경되었습니다.");
                    dispose();
                } catch (FileNotFoundException ex) {
                    Logger.getLogger(ChangeUser.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(ChangeUser.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "비밀번호가 변경되지 않았습니다.");
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (userCheck == false) {
            JOptionPane.showMessageDialog(null, "인증이 완료되지 않았습니다. 인증 후 다시 시도해주십시요");
        } else {
            int result = JOptionPane.showConfirmDialog(null, "회원을 탈퇴하시겠습니까?", "주의!", JOptionPane.YES_NO_OPTION);
            if (result == JOptionPane.CLOSED_OPTION) {
                JOptionPane.showMessageDialog(null, "회원 탈퇴를 하지 않았습니다.");
            } else if (result == JOptionPane.YES_OPTION) {
                
                String temp;
                String[] array = new String[4];
                String dummy = "";
                
                try {

                    BufferedReader reader = new BufferedReader(new InputStreamReader(new FileInputStream(myFile)));

                    while ((temp = reader.readLine()) != null) {
                        array = temp.split("/");
                        if (!id.getText().equals(array[1]) && !pw.getText().equals(array[2])) {
                            dummy += (temp + "\r\n");
                        }
                    }

                    FileWriter fw = new FileWriter("User.txt");
                    fw.write(dummy);

                    reader.close();
                    fw.close();
                    JOptionPane.showMessageDialog(null, "회원 탈되가 완료되었습니다.");
                    dispose();
                } catch (IOException ex) {
                    Logger.getLogger(ChangeUser.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else {
                JOptionPane.showMessageDialog(null, "회원 탈퇴를 하지 않았습니다.");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChangeUser.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChangeUser.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChangeUser.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChangeUser.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChangeUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPasswordField newpw;
    private javax.swing.JPasswordField newpwCheck;
    private javax.swing.JPasswordField pw;
    // End of variables declaration//GEN-END:variables
}
