/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.BufferedReader;
import java.io.File;
import javax.swing.JOptionPane;
import java.io.*;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Free
 */
public class checkout extends javax.swing.JFrame {
    File file = new File("Reservation.txt"); 
    File asfile= new File("menu.txt"); 
    File stayfile= new File("stay.txt"); 
    File roomfile = new File("rom.txt");
    File managementfile = new File("management.txt");
    int roomcash ;
    int restaurantpay;
    int sum;
    String paytype;

    public int add() {
        Calendar cal = Calendar.getInstance();
        int houra = cal.get(Calendar.HOUR_OF_DAY);
        int sum = 0;
        int CheckOutTime = 11;
        int AddPay = 10000;
        if (houra > CheckOutTime) {
            int overtime = houra - CheckOutTime;
            for (int i = 0; i < overtime; i++) {
                sum = sum + AddPay;
            }
        }
        return sum;
    }

    /**
     * Creates new form checkout
     */
    public checkout() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null); //자동으로 가운데에서 출력됨
        setDefaultCloseOperation(EXIT_ON_CLOSE); //프로그램을 껐을 때 모든 것이 종료되는 것
        jPanel2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        payInfo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        list = new javax.swing.JTextArea();
        roomnum = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        userInfo = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        checknum = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane3.setViewportView(jTextArea1);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane4.setViewportView(jTextArea2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("지불할 금액:");

        jLabel3.setText("고객의견");

        list.setColumns(20);
        list.setRows(5);
        jScrollPane1.setViewportView(list);

        jButton4.setText("확인");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel5.setText("객실번호 ");

        jLabel6.setText("고객정보 검색");

        jLabel8.setText("고객 정보:");

        jButton3.setText("계산서 출력");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel18.setText("고유 번호");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addComponent(jLabel1))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(payInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(roomnum, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel18)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(checknum, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(93, 93, 93)
                                    .addComponent(jLabel6)))
                            .addGap(18, 18, 18)
                            .addComponent(jButton4))
                        .addComponent(userInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(roomnum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checknum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18)))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userInfo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(payInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 2, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jButton1.setText("계산 및 체크아웃");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel4.setText("총 지불하실 금액");

        jLabel11.setText("객실요금");

        jLabel13.setText("식당요금");

        jLabel15.setText("추가부과금");

        jLabel17.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jLabel17.setText("계산서");

        jLabel19.setText("결제 종류");

        jButton2.setText("뒤로가기");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(43, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addGap(116, 116, 116))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap())))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel17)
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        Date today = new Date();

        SimpleDateFormat time = new SimpleDateFormat("a hh:mm:ss");
        SimpleDateFormat date = new SimpleDateFormat("yyyy/MM/dd");
        JOptionPane.showMessageDialog(null, "현제 시간이 " + time.format(today) + "이므로 체크아웃을 진행하실 경우 " + add() + "의 추가숙박료가 부과 됩니다.");

        jPanel2.setVisible(true);
        int activepay=sum+add();
        String addpay=Integer.toString(add());
        String realpay=Integer.toString(activepay);
        
        
        jLabel9.setText(realpay);
        jLabel12.setText(Integer.toString(roomcash)); 
        jLabel14.setText(Integer.toString(restaurantpay)); 
        jLabel16.setText(addpay);
        jLabel20.setText(paytype);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

 
            String temps = ""; //행을 읽어올 때마다 각 행을 저장하기 위한 String 변수를 만듬
            String[] resulta;
            FileInputStream opinion;
            FileInputStream pay;
            FileInputStream roomPay;
            FileInputStream payhow;
        try {
            opinion = new FileInputStream(stayfile);//텍스트 파일로 연결되는 문자를 위한 연결 스트림 
            InputStreamReader isr = new InputStreamReader(opinion);
            BufferedReader stayreader = new BufferedReader(isr); //읽기 작업의 효유를 향상시키위함
            while ((temps = stayreader.readLine()) != null) {
               resulta = temps.split("/"); //텍스트 한 행을 읽은 다음 그 행을 line이라는 String 변수에 저장하는 부분-대상 변수가  null이 아니면 방금 읽어온 것을 출력함 아니면 "읽을 행이 아직 남아있으면 읽어온 다음 출력하라" 
                if (roomnum.getText().equals(resulta[0]) && checknum.getText().equals(resulta[7])) {
                    JOptionPane.showMessageDialog(null, "확인되었습니다.");
                    userInfo.setText(resulta[1] + "-" + resulta[2]);
                }
            }
            
            stayreader.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(checkout.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(checkout.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        String temp = "";
        String[] result;
        try {
            pay = new FileInputStream(asfile); //텍스트 파일로 연결되는 문자를 위한 연결 스트림
            InputStreamReader resisp = new InputStreamReader(pay); 
            BufferedReader paynum = new BufferedReader(resisp); //읽기 작업의 효유를 향상시키위함
             //행을 읽어올 때마다 각 행을 저장하기 위한 String 변수를 만듬
            while ((temp = paynum.readLine()) != null) {
                result = temp.split("/"); //텍스트 한 행을 읽은 다음 그 행을 line이라는 String 변수에 저장하는 부분-대상 변수가  null이 아니면 방금 읽어온 것을 출력함 아니면 "읽을 행이 아직 남아있으면 읽어온 다음 출력하라" 
                if (roomnum.getText().equals(result[0]) && checknum.getText().equals(result[1])) {
                    restaurantpay=Integer.parseInt(result[4]);
                }
            }
            paynum.close();
            
            String roompaytemp="";
            String[] roompayArray;
            String roomclass;
            
            roomPay = new FileInputStream(stayfile); //텍스트 파일로 연결되는 문자를 위한 연결 스트림
            InputStreamReader stayisp = new InputStreamReader(roomPay); 
            BufferedReader roompay = new BufferedReader(stayisp);
            
             while ((roompaytemp = roompay.readLine()) != null) {
                roompayArray = roompaytemp.split("/"); //텍스트 한 행을 읽은 다음 그 행을 line이라는 String 변수에 저장하는 부분-대상 변수가  null이 아니면 방금 읽어온 것을 출력함 아니면 "읽을 행이 아직 남아있으면 읽어온 다음 출력하라" 
                if (roomnum.getText().equals(roompayArray[0]) && checknum.getText().equals(roompayArray[7])) {
                    roomclass = roompayArray[8];
                    switch (roomclass) {
                        case "1":
                            roomcash = 200000;
                            break;
                        case "2":
                            roomcash = 150000;
                            break;
                        default:
                            roomcash = 100000;
                            break;
                    }
                   
                }
            }
             
            sum=restaurantpay+roomcash;
            String pays=Integer.toString(sum);
            payInfo.setText(pays);
            
            roompay.close();
            
            String payinfo;
            String[] payArray;
            payhow = new FileInputStream(stayfile); //텍스트 파일로 연결되는 문자를 위한 연결 스트림
            InputStreamReader payisr = new InputStreamReader(payhow); 
            BufferedReader paybr = new BufferedReader(payisr);
            
            while((payinfo = paybr.readLine()) != null){
                payArray = payinfo.split("/");
                if(roomnum.getText().equals(payArray[0]) && checknum.getText().equals(payArray[7])){
                    paytype = payArray[3];
                }
            }
            paybr.close();
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(checkout.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(checkout.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //menu, stay, room 파일
        Date today = new Date();

        SimpleDateFormat checkouttime = new SimpleDateFormat("a hh:mm:ss");
        SimpleDateFormat checkoutdate = new SimpleDateFormat("yyyy/MM/dd");
        
        String temps;
        String[] resulta;
        String dummy = "";
        FileInputStream opinion;
        FileInputStream pay;
        FileInputStream roomcheck;
        FileInputStream management;
        try {
            opinion = new FileInputStream(stayfile);
            InputStreamReader isr = new InputStreamReader(opinion);
            BufferedReader stayreader = new BufferedReader(isr);
            
            while ((temps = stayreader.readLine()) != null) {
               resulta = temps.split("/"); 
                if (!roomnum.getText().equals(resulta[0]) && !checknum.getText().equals(resulta[7])) {
                    dummy += (temps + "\r\n");
                }  
            }
            FileWriter stayfw = new FileWriter("stay.txt");
            stayfw.write(dummy);
            stayfw.close();
            stayreader.close();
            
            
            String temp;
            String[] result;
            String menudummy = "";
            pay = new FileInputStream(asfile);
            InputStreamReader resisp = new InputStreamReader(pay); 
            BufferedReader paynum = new BufferedReader(resisp);
            
            while ((temp = paynum.readLine()) != null) {
                result = temp.split("/");  
                if (!roomnum.getText().equals(result[0]) && !checknum.getText().equals(result[1])) {
                    menudummy += (temp + "\r\n");
                }
            }
            FileWriter menufw = new FileWriter("menu.txt");
            menufw.write(menudummy);
            menufw.close();
            stayreader.close();
            
            
            String roomtemp;
            String[] roomArray;
            String roomdummy = "";
            roomcheck = new FileInputStream(roomfile);
            InputStreamReader roomisp = new InputStreamReader(roomcheck); 
            BufferedReader roomstate = new BufferedReader(roomisp);
            while ((roomtemp = roomstate.readLine()) != null) {
                roomArray = roomtemp.split("/");  
                if (roomnum.getText().equals(roomArray[0]) && roomArray[3].equals("숙박중")) {
                    roomtemp = roomtemp.replace("숙박중", "비어있음");
                }
                roomdummy += roomtemp + "\r\n";
            }
            FileWriter roomfw = new FileWriter("Rom.txt");
            roomfw.flush();
            roomfw.write(roomdummy);
            roomstate.close();
            roomfw.close();
            if(jLabel20.getText().equals("현금")){
                JOptionPane.showMessageDialog(null, "현금으로 결제가 되었습니다. 체크아웃이 완료 되었습니다. \n 체크아웃 날짜 : " + checkoutdate.format(today) + "\n체크아웃 시간 : " + checkouttime.format(today));          
            }else{
                JOptionPane.showMessageDialog(null, "카드로 결제가 되었습니다. 체크아웃이 완료 되었습니다.\n 체크아웃 날짜 : " + checkoutdate.format(today) + "\n체크아웃 시간 : " + checkouttime.format(today));
            }
            
            int num1;
            int num2;
            int num3;
            int num4;
            
            String managementtemp;
            String[] managementArray;
            String managementdummy = "";
            management = new FileInputStream(managementfile);
            InputStreamReader managementisp = new InputStreamReader(management); 
            BufferedReader managementreader = new BufferedReader(managementisp);
            
            managementtemp = managementreader.readLine();
            managementArray = managementtemp.split("/");
            num1 = Integer.parseInt(managementArray[0]) + Integer.parseInt(jLabel12.getText());
            num2 = Integer.parseInt(managementArray[1]) + Integer.parseInt(jLabel14.getText());
            num3 = Integer.parseInt(managementArray[2]) + Integer.parseInt(jLabel16.getText());
            num4 = Integer.parseInt(managementArray[5]) + 1;
            managementArray[0] = Integer.toString(num1) + "/";
            managementArray[1] = Integer.toString(num2) + "/";
            managementArray[2] = Integer.toString(num3) + "/";
            managementArray[3] = Double.toString((float)(num4/3100)*100) + "/";
            managementArray[4] = Float.toString((float)(2000.0/3100.0)*100) + "/";
            managementArray[5] = Integer.toString(num4) + "/";
            for(int i=0; i<6; i++){
                managementdummy += managementArray[i];
            }
            FileWriter managementfw = new FileWriter("management.txt");
            managementfw.write(managementdummy);
            managementfw.close();
            stayreader.close();
            dispose();
            
            
        } catch (FileNotFoundException ex) {
            Logger.getLogger(checkout.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(checkout.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(checkout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new checkout().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField checknum;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea list;
    private javax.swing.JLabel payInfo;
    private javax.swing.JTextField roomnum;
    private javax.swing.JLabel userInfo;
    // End of variables declaration//GEN-END:variables
}
