/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import javax.swing.JOptionPane;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author tlatl
 */
public class Login extends javax.swing.JFrame {
    File hostfile = new File("host.txt");
    File myFile = new File("User.txt");
    boolean check = false;
    boolean hostcheck = false;
    String[] loginArray;
    public static String LoginState;
    
    /**
     * Creates new form ch03
     */
    public Login() {
        initComponents();
        setTitle("호텔 관리 프로그램");
        setSize(900,550);
        setResizable(false);
        setLocationRelativeTo(null);
        
    }
    
    public String getLoginState(){
        return LoginState;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        pw = new javax.swing.JPasswordField();
        jButton3 = new javax.swing.JButton();
        manager = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 530));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("맑은 고딕", 1, 36)); // NOI18N
        jLabel1.setText("Hotel System");
        jLabel1.setToolTipText("");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.setName(""); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 230, -1));

        jButton1.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        jButton1.setText("로그인");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 90, 80));

        jLabel2.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        jLabel2.setText("ID : ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, 20));

        jLabel3.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        jLabel3.setText("Password : ");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, 30));

        id.setFont(new java.awt.Font("맑은 고딕", 0, 14)); // NOI18N
        jPanel2.add(id, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 110, 190, 30));

        jButton2.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        jButton2.setText("회원가입");
        jButton2.setMaximumSize(new java.awt.Dimension(113, 25));
        jButton2.setMinimumSize(new java.awt.Dimension(113, 25));
        jButton2.setPreferredSize(new java.awt.Dimension(113, 25));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, 30));

        jButton4.setFont(new java.awt.Font("맑은 고딕", 0, 12)); // NOI18N
        jButton4.setText("프로그램 종료");
        jButton4.setMaximumSize(new java.awt.Dimension(113, 25));
        jButton4.setMinimumSize(new java.awt.Dimension(113, 25));
        jButton4.setPreferredSize(new java.awt.Dimension(113, 25));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, 30));
        jPanel2.add(pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 190, 30));

        jButton3.setText("회원정보 수정");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 120, 30));

        manager.setText("관리자");
        jPanel2.add(manager, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 460, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        Membership ms = new Membership();
        ms.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int result = JOptionPane.showConfirmDialog(null, "프로그램을 종료하시겠습니까?","Confirm",JOptionPane.YES_NO_OPTION);
        if(result == JOptionPane.YES_OPTION) {
            System.exit(0); // 프레임을 종료한다
        } else if ((result == JOptionPane.NO_OPTION) || (result == JOptionPane.CLOSED_OPTION )) {
           return ; // 아무 작업도 하지 않고 다이얼로그 상자를 닫는다
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FileInputStream hostfis;
        try{
            FileReader fileReader = new FileReader(myFile);
            BufferedReader reader = new BufferedReader(fileReader);
            
            if(id.getText().length() == 0){
                JOptionPane.showMessageDialog(null, "아이디가 입력되지 않았습니다.");
            }
            else if(pw.getText().length() == 0){
                JOptionPane.showMessageDialog(null, "패스워드가 입력되지 않았습니다.");
            }
            else if(id.getText().length() == 0||pw.getText().length() == 0){
                JOptionPane.showMessageDialog(null, "아이디, 패스워드가 입력되지 않았습니다.");
            }
            
            if(manager.isSelected()){
                String hosttemp;
                String[] hostArray;
                hostfis = new FileInputStream(hostfile);//텍스트 파일로 연결되는 문자를 위한 연결 스트림 
                InputStreamReader hostisr = new InputStreamReader(hostfis);
                BufferedReader hostreader = new BufferedReader(hostisr);
                
                while((hosttemp= hostreader.readLine()) != null){
                    hostArray = hosttemp.split("/");
                    if(id.getText().equals(hostArray[1]) && pw.getText().equals(hostArray[2])){
                        JOptionPane.showMessageDialog(null, "관리자 인증이 완료되었습니다.\n 관리자 페이지로 이동합니다.");
                        id.setText("");
                        pw.setText("");
                        HostHome sh = new HostHome();
                        sh.setVisible(true);
                        hostcheck = true;
                        break;
                    }
                }
                if(hostcheck == false) {
                    JOptionPane.showMessageDialog(null, "관리자 로그인에 실패하였습니다.");
                    id.setText("");
                    pw.setText("");
                }
                    
                hostreader.close();
            }else{
                
                String temp;
            
                while((temp = reader.readLine()) != null){
                    loginArray = temp.split("/");
                    if(id.getText().equals(loginArray[1]) && pw.getText().equals(loginArray[2])){
                        JOptionPane.showMessageDialog(null, "로그인 되었습니다.");
                        LoginState = loginArray[0] +"/"+ loginArray[4]+"/";
                        id.setText("");
                        pw.setText("");
                        ShowHome sh = new ShowHome();
                        sh.setVisible(true);
                        check = true;
                        break;
                    }
                }
            if(check == false){
                JOptionPane.showMessageDialog(null, "로그인에 실패하였습니다.");
                id.setText("");
                pw.setText("");
            }
                reader.close();
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        ChangeUser cu = new ChangeUser();
        cu.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton manager;
    private javax.swing.JPasswordField pw;
    // End of variables declaration//GEN-END:variables
}
